### ISSUE TITLE
Wrong Hyperdrive logo

### ISSUE THREAD

**Issue by LozadaLuis12** [DefiLlama/icons#2080]
After checking the new HyperDrive X account and how DELV is only providing an UI to access Hyperdrive, wanted to point out that DeFillama should change Hyperdrive's logo to not be DELV's one.
![image](https://github.com/user-attachments/assets/b97fee9a-3493-4914-b3e8-2f9922f32ac6)

Instead of the logo it should be this one: 
![Hyperdrive Logomark](https://github.com/user-attachments/assets/86cd78c6-6b62-42f7-ac34-f7240269383d)

You can also check's Hyperdrive's app to see the logo is not matching the real one.

I'm referring to the following icon page here on Github: https://github.com/DefiLlama/icons/blob/v2/assets/protocols/hyperdrive.jpg 

Tried to do a PR but wasn't able to.

Thanks!

**Comment by realdealshaman** [comment]
Hey, @LozadaLuis12 thanks for the ping! I've now updated the logo, new one will be live in about one hour
![image](https://github.com/user-attachments/assets/2df938c6-a644-401a-acde-73f831585a6e)
