### ISSUE TITLE
Unkown-logo displayed for Arthera Testnet

### ISSUE THREAD

**Issue by lperello** [DefiLlama/icons#858]
The displayed logo for Arthera Testnet is not the one configured for Chainid.network by PR https://github.com/ethereum-lists/chains/pull/3005
As advised in issue https://github.com/ethereum-lists/chains/issues/3572 , could you please update the icon using the official one 
https://docs.arthera.net/assets/files/gradient_icon-d478e08e6bd7027efe7b422e7b262ad0.png

![image](https://github.com/DefiLlama/icons/assets/136899480/168d9bae-e2b7-4b44-8e50-6d72b76a2d4e)

Thank you in advance

**Comment by realdealshaman** [comment]
Hey, this is working as intended, we only add the logo to chains that are already listed on DefiLlama
